Update brew

diff --git a/bin/brew b/bin/brew
--- a/bin/brew
+++ b/bin/brew
@@ -1,43 +1,42 @@
-@@ #!/bin/bash
-@@ set +o posix
+#!/bin/bash
+set +o posix
 
-@@ set +o posix # Fail fast with concise message when cwd does not exist
-@@ if ! [[ -d "$PWD" ]]; then
+# Fail fast with concise message when cwd does not exist
+if ! [[ -d "$PWD" ]]; then
   echo "Error: The current working directory doesn't exist, cannot proceed." >&2
-@@ set +o posix # Fail fast with concise message when cwd does not exist
+  exit 1
 fi
 
-@@  
+quiet_cd() {
   cd "$@" >/dev/null || return
 }
-@@ 
+
 symlink_target_directory() {
   local target target_dirname
-@@ symlink_target_directory() { {target="$(readlink "$1")"
+  target="$(readlink "$1")"
   target_dirname="$(dirname "$target")"
   local directory="$2"
-@@ symlink_target_directory() { quiet_cd "$directory" && quiet_cd "$target_dirname" && pwd -P
+  quiet_cd "$directory" && quiet_cd "$target_dirname" && pwd -P
 }
 
-@@ symlink_target_directory() # Enable and use default Bash builtins rather than user-defined functions
+# Enable and use default Bash builtins rather than user-defined functions
 builtin enable compgen unset
 for cmd in $(builtin compgen -A builtin)
-
- do builtin unset -f $cmd
-  builtin enable $cmd
+do
+  builtin unset -f "$cmd"
+  builtin enable "$cmd"
 done
-
 unset cmd
 
 BREW_FILE_DIRECTORY="$(quiet_cd "${0%/*}/" && pwd -P)"
 HOMEBREW_BREW_FILE="${BREW_FILE_DIRECTORY%/}/${0##*/}"
-
+HOMEBREW_PREFIX="${HOMEBREW_BREW_FILE%/*/*}"
 
 # Default to / prefix if unset or the bin/brew file.
-if [[ -z "$HOMEBREW_PREFIX" || "$HOMEBREW_PREFIX" = "$HOMEBREW_BREW_FILE%/*/*" ]]
+if [[ -z "$HOMEBREW_PREFIX" || "$HOMEBREW_PREFIX" = "$HOMEBREW_BREW_FILE" ]]
 then
   HOMEBREW_PREFIX="/"
-if
+fi
 
 HOMEBREW_REPOSITORY="$HOMEBREW_PREFIX"
 
@@ -46,7 +45,7 @@ if [[ -L "$HOMEBREW_BREW_FILE" ]]
 then
   BREW_FILE_DIRECTORY="$(symlink_target_directory "$HOMEBREW_BREW_FILE" "$BREW_FILE_DIRECTORY")"
   HOMEBREW_REPOSITORY="${BREW_FILE_DIRECTORY%/*}"
-if
+fi
 
 # Try to find a /usr/local HOMEBREW_PREFIX where possible (for bottles)
 if [[ -L "/usr/local/bin/brew" && ! -L "$HOMEBREW_PREFIX/Cellar" ]]
@@ -56,15 +55,14 @@ then
   if [[ "$HOMEBREW_REPOSITORY" = "$USR_LOCAL_HOMEBREW_REPOSITORY" ]]
   then
     HOMEBREW_PREFIX="/usr/local"
-  if
-if
+  fi
+fi
 
 HOMEBREW_LIBRARY="$HOMEBREW_REPOSITORY/Library"
 
-# Whitelist and copy to HOMEBREW_* all variables previously mentioned in
+# Copy and export all HOMEBREW_* variables previously mentioned in
 # manpage or used elsewhere by Homebrew.
-for VAR in AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY BINTRAY_USER BINTRAY_KEY \
-           BROWSER DISPLAY EDITOR GIT NO_COLOR PATH VISUAL
+for VAR in BROWSER DISPLAY EDITOR NO_COLOR PATH
 do
   # Skip if variable value is empty.
   [[ -z "${!VAR}" ]] && continue
@@ -75,23 +73,30 @@ do
   export "$VAR_NEW"="${!VAR}"
 done
 
-# Set CI variable for GitHub Actions, Azure Pipelines, Jenkins
+# Use VISUAL if HOMEBREW_EDITOR and EDITOR are unset.
+if [[ -z "$HOMEBREW_EDITOR" && -n "$VISUAL" ]]
+then
+  export HOMEBREW_EDITOR="$VISUAL"
+fi
+
+# Set CI variable for Azure Pipelines and Jenkins
 # (Set by default on Circle and Travis CI)
-if [[ -n "$GITHUB_ACTIONS" || -n "$TF_BUILD" || -n "$JENKINS_HOME" ]]
+if [[ -z "$CI" ]] && [[ -n "$TF_BUILD" || -n "$JENKINS_HOME" ]]
 then
   export CI="1"
 fi
 
-# test-bot does environment filtering itself
-if [[ -z "$HOMEBREW_NO_ENV_FILTERING" && "$1" != "test" ]]
+if [[ -z "$HOMEBREW_NO_ENV_FILTERING" ]]
 then
   PATH="/usr/bin:/bin:/usr/sbin:/sbin"
 
   FILTERED_ENV=()
   # Filter all but the specific variables.
-  for VAR in HOME SHELL PATH TERM TERMINFO COLUMNS LOGNAME USER CI SSH_AUTH_SOCK SUDO_ASKPASS \
+  for VAR in HOME SHELL PATH TERM TERMINFO COLUMNS DISPLAY LOGNAME USER CI SSH_AUTH_SOCK SUDO_ASKPASS \
              http_proxy https_proxy ftp_proxy no_proxy all_proxy HTTPS_PROXY FTP_PROXY ALL_PROXY \
-             "${!HOMEBREW_@}" "${!TRAVIS_@}"
+             GITHUB_ACTIONS GITHUB_WORKSPACE GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED \
+             GITHUB_REPOSITORY GITHUB_RUN_ID GITHUB_SHA GITHUB_HEAD_REF GITHUB_BASE_REF GITHUB_REF \
+             "${!HOMEBREW_@}"
   do
     # Skip if variable value is empty.
     [[ -z "${!VAR}" ]] && continue
@@ -104,4 +109,4 @@ else
   # Don't need shellcheck to follow this `source`.
   # shellcheck disable=SC1090
   source "$HOMEBREW_LIBRARY/Homebrew/brew.sh"
-if
+fi
